version: "3.9"
services:
  api:
    build:
      context: ./EnergyBalancesApi   # root projektu API
      dockerfile: ../docker/Dockerfile   # ścieżka względem compose
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: EnergyDb
    volumes:
      - db_data:/var/lib/mysql
     -- ./docker/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  db_data:
